name: RyanNorthcutt
favicon: null
layout_spectrum: 0.44884374109096825
typography_spectrum: 0.8095641043037176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.40109281172044575
  lightness: 0.92102951859124
  saturation: 0.11009717755950987
  rhythmicContrast: 0.21509401872754097
purpose: []
